// Dados a serem utilizados caso tenha problemas com o SQLite

$data = [
    [
        'id' => 1,
        'type' => 'duvida',
        'message' => 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
        'is_identified' => false,
        'whistleblower_name' => null,
        'whistleblower_birth' => null,
        'created_at' => '2021-06-30 18:47:23',
        'deleted' => true,
    ],
    [
        'id' => 2,
        'type' => 'duvida',
        'message' => 'Donec ut mauris eget massa tempor convallis.',
        'is_identified' => true,
        'whistleblower_name' => 'Carly Insko',
        'whistleblower_birth' => '1988-03-19',
        'created_at' => '2020-12-19 09:55:55',
        'deleted' => true,
    ],
    [
        'id' => 3,
        'type' => 'sugestao',
        'message' => 'In blandit ultrices enim.',
        'is_identified' => true,
        'whistleblower_name' => 'Parsifal Dorkens',
        'whistleblower_birth' => '1983-02-19',
        'created_at' => '2020-09-04 12:41:53',
        'deleted' => false,
    ],
    [
        'id' => 4,
        'type' => 'denuncia',
        'message' => 'Donec semper sapien a libero.',
        'is_identified' => false,
        'whistleblower_name' => null,
        'whistleblower_birth' => null,
        'created_at' => '2020-12-05 21:59:01',
        'deleted' => false,
    ],
    [
        'id' => 5,
        'type' => 'denuncia',
        'message' => 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.',
        'is_identified' => false,
        'whistleblower_name' => null,
        'whistleblower_birth' => null,
        'created_at' => '2021-02-08 10:18:37',
        'deleted' => false,
    ],
    [
        'id' => 6,
        'type' => 'duvida',
        'message' => 'Phasellus sit amet erat.',
        'is_identified' => false,
        'whistleblower_name' => null,
        'whistleblower_birth' => null,
        'created_at' => '2020-08-31 20:53:33',
        'deleted' => false,
    ],
    [
        'id' => 7,
        'type' => 'denuncia',
        'message' => 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
        'is_identified' => false,
        'whistleblower_name' => null,
        'whistleblower_birth' => null,
        'created_at' => '2020-12-21 21:55:40',
        'deleted' => true,
    ],
    [
        'id' => 8,
        'type' => 'sugestao',
        'message' => 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
        'is_identified' => true,
        'whistleblower_name' => 'Frances Petit',
        'whistleblower_birth' => '1997-06-12',
        'created_at' => '2021-05-12 14:25:24',
        'deleted' => false,
    ],
    [
        'id' => 9,
        'type' => 'denuncia',
        'message' => 'Integer a nibh.',
        'is_identified' => false,
        'whistleblower_name' => null,
        'whistleblower_birth' => null,
        'created_at' => '2021-07-10 20:27:29',
        'deleted' => false,
    ],
    [
        'id' => 10,
        'type' => 'sugestao',
        'message' => 'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.',
        'is_identified' => true,
        'whistleblower_name' => 'Bar Rannigan',
        'whistleblower_birth' => '2001-12-30',
        'created_at' => '2020-10-03 17:13:22',
        'deleted' => false,
    ]
];